Update requirements.txt
When running in a new virtual environment portable.py requires requests module.

adding requests module to the requirements.txt file will fix this for those running pip3 install -r requirements.txt

(.env) (base) justin@Justins-MBP 13ft % python portable.py 
Traceback (most recent call last):
  File "/Users/justin/GitHub/13ft/portable.py", line 2, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'